### ISSUE TITLE
MoviePy error: FFMPEG encountered the following error while writing file /edited_videos/millennials.mp4:

### ISSUE THREAD

**Issue by RealStJimmy** [brycerohrer/reddit_video_maker#7]
When i try to run the automate.sh script i get this

` 
Moviepy - Building video /edited_videos/millennials.mp4.
MoviePy - Writing audio in temp-audio.m4a
MoviePy - Done.
Moviepy - Writing video /edited_videos/millennials.mp4

t:   1%|▊                                                                                                                                          | 2/370 [00:00<00:22, 16.58it/s, now=None]
Traceback (most recent call last):
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 63, in <module>
    exit(main())
  File "run.py", line 55, in main
    Editor.create_movie()
  File "/home/stjimmy/PythonProject/videomaker/reddit_video_maker/src/VideoEdit.py", line 50, in create_movie
    final_vid.write_videofile(f'{self.save_path}{self.video_name}.mp4',
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/home/stjimmy/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file /edited_videos/millennials.mp4:

 b'/edited_videos/millennials.mp4: No such file or directory\n'
Creating video for:
usage: run.py [-h] url n_entries video_name
run.py: error: the following arguments are required: url, n_entries, video_name
`

**Comment by alexshelto** [comment]
Interesting bug. I will try to recreate this issue. Do you currently have ffmpeg on your system. Are you using a virtual environment with all of the requirements installed?

**Comment by RealStJimmy** [comment]
Yes
and initially it was not in a virtualenv but I did it again in a virtualenv and the issue persists.
Running Ubuntu 20.04 LTS and Python 3.8.5 if that means anything
